export const ACCESS_CODE_REQUEST = 'ACCESS_CODE_REQUEST';
export const ACCESS_CODE_SUCCESS = 'ACCESS_CODE_SUCCESS';
export const ACCESS_CODE_FAILURE = 'ACCESS_CODE_FAILURE';

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

export const CLEAR_ACCESS_CODE_DATA = 'CLEAR_ACCESS_CODE_DATA';
