export const FETCH_VENDOR_BY_STATUS_REQUEST = "FETCH_VENDOR_BY_STATUS_REQUEST";
export const FETCH_VENDOR_BY_STATUS_SUCCESS = "FETCH_VENDOR_BY_STATUS_SUCCESS";
export const FETCH_VENDOR_BY_STATUS_FAILURE = "FETCH_VENDOR_BY_STATUS_FAILURE";

